x-service-templates:
  backend: &backend
    image: githiago/rinha2025:3.0.0
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "140MB"

services:
  nginx:
    image: nginx
    networks:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 9999:9999
    depends_on:
      - backend1
      - backend2
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "70MB"
  backend1:
    <<: *backend
    hostname: backend1
    ports:
      - 8080:9999
    environment:
      PAYMENT_PROCESSOR_API_URL: http://payment-processor-default:8080
      PAYMENT_PROCESSOR_FALLBACK_URL: http://payment-processor-fallback:8080
      PAYMENT_PROCESSOR_IS_LEADER: true
      PAYMENT_PROCESSOR_CHECK_TIMING: 5s
      PAYMENT_PROCESSOR_WORKERS: 16
  backend2:
    <<: *backend
    hostname: backend2
    environment:
      PAYMENT_PROCESSOR_API_URL: http://payment-processor-default:8080
      PAYMENT_PROCESSOR_FALLBACK_URL: http://payment-processor-fallback:8080
      PAYMENT_PROCESSOR_LEADER_HOST: backend1
      PAYMENT_PROCESSOR_WORKERS: 16
    ports:
      - 8081:9999

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true