services:
  lbproxy:
    image: enermaxx/lb-novo-undertow:2.0.7
    container_name: lb-proxy
    environment:
      - API_1_HOST=api1
      - API_1_PORT=8080
      - API_2_HOST=api2
      - API_2_PORT=8080
      - LB_PORT=9999
    ports:
      - "9999:9999"
    depends_on:
      - api1
      - api2
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "1.2"
          memory: "150MB"
  api1: &api
    image: enermaxx/rinha-backend:4.0.4
    container_name: springboot-api1
    hostname: api1
    ports:
      - "7777:8080"
    environment:
      - HOST_TO_LOCK=api2
      - PORT_TO_LOCK=8080
      - MAIN_PROCESSOR_HOST=payment-processor-default
      - MAIN_PROCESSOR_PORT=8080
      - FALLBACK_PROCESSOR_HOST=payment-processor-fallback
      - FALLBACK_PROCESSOR_PORT=8080
      - INSTANCE_ID=API-1
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "100MB"

  api2:
    <<: *api
    container_name: springboot-api2
    hostname: api2
    ports:
      - "7778:8080"
    environment:
      - HOST_TO_LOCK=api1
      - PORT_TO_LOCK=8080
      - MAIN_PROCESSOR_HOST=payment-processor-default
      - MAIN_PROCESSOR_PORT=8080
      - FALLBACK_PROCESSOR_HOST=payment-processor-fallback
      - FALLBACK_PROCESSOR_PORT=8080
      - INSTANCE_ID=API-2
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "100MB"
networks:
  backend:
    driver: bridge
  payment-processor:
    external: true