services:
  redis:
    image: redis:7.2-alpine
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - rinha-net
    volumes:
      - redis-data:/data
    command: [
      "redis-server",
      "--save", "",
      "--appendonly", "no",
      "--databases", "1",
      "--loglevel", "warning",
      "--logfile", "/dev/null",
      "--tcp-keepalive", "60"
    ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "25MB"



  # Produtores ========================================================================
  api01: &api
    image: 442494/rinha-backend-2025-produtor:v2
    hostname: api01
    networks:
      - rinha-net
      - payment-processor
    ports:
      - "8081:8080"  
    environment:
      # - QUARKUS_HTTP_PORT=8080
      - QUARKUS_REDIS_HOST=redis://redis:6379
      - PAYMENT_PROCESSOR_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK=http://payment-processor-fallback:8080
      - QUARKUS_LOG_LEVEL=INFO
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

  api02:
    <<: *api 
    networks:
      - rinha-net
      - payment-processor
    hostname: api02
    ports:
      - "8082:8080"
    environment:
      # - QUARKUS_HTTP_PORT=8080
      - QUARKUS_REDIS_HOST=redis://redis:6379
      - PAYMENT_PROCESSOR_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK=http://payment-processor-fallback:8080
      - QUARKUS_LOG_LEVEL=INFO
  # Produtores ========================================================================

  # Consumidores ========================================================================
  api03:
    image: 442494/rinha-backend-2025-consumidor:v2
    hostname: api03
    networks:
      - rinha-net
      - payment-processor
    ports:
      - "8083:8080"  
    environment:
      # - QUARKUS_HTTP_PORT=8080
      - QUARKUS_REDIS_HOST=redis://redis:6379
      - PAYMENT_PROCESSOR_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK=http://payment-processor-fallback:8080
      - QUARKUS_LOG_LEVEL=INFO
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"

  # Consumidores ========================================================================

  nginx:
    image: nginx:latest
    networks:
      - rinha-net
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
     
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "25MB"


networks:
  payment-processor:
    external: true
  rinha-net:
    driver: bridge

volumes:
  redis-data:
