services:
  nginx:
    image: nginx:1.25-alpine
    container_name: rinha-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - rinha_payment-processor
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "55MB"

  api1:
    image: danielsuhett1999/rinha-backend:1.0.2
    hostname: api1
    environment:
      - APP_PORT=8080
      - APP_NAME=1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - LOG_LEVEL=ERROR
    networks:
      - backend
      - rinha_payment-processor
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "120MB"

  api2:
    image: danielsuhett1999/rinha-backend:1.0.2
    hostname: api2
    environment:
      - APP_PORT=8081
      - APP_NAME=2
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - LOG_LEVEL=ERROR
    networks:
      - backend
      - rinha_payment-processor
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "120MB"

  redis:
    image: redis:7.2-alpine
    container_name: rinha-redis
    command: redis-server --save "" --appendonly no --maxmemory 45mb --maxmemory-policy allkeys-lru --tcp-keepalive 30 --timeout 0 --tcp-backlog 1024 --databases 1 --maxclients 5000 --hz 10 --rdbcompression no --rdbchecksum no --io-threads 2 --io-threads-do-reads yes
    networks:
      - backend
    ports:
      - 6380:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "50MB"

networks:
  backend:
    driver: bridge
  rinha_payment-processor:
    external: true
