services:
  write_api: &api-service
    image: eber404/dudebank:0.0.7
    env_file:
      - .env
    environment:
      - SERVER_SOCKET_PATH=/tmp/write_api.sock
    networks:
      - backend
      - payment-processor
    volumes:
      - socket_data:/tmp
    depends_on:
      - database
    deploy:
      resources:
        limits:
          cpus: '1.25'
          memory: '275MB'

  read_api:
    <<: *api-service
    environment:
      - SERVER_SOCKET_PATH=/tmp/read_api.sock
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '40MB'

  database:
    image: eber404/dudebank-db:0.0.7
    volumes:
      - socket_data:/tmp
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: '15MB'

  nginx:
    image: openresty/openresty:bullseye
    env_file:
      - .env
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - socket_data:/tmp
    depends_on:
      - write_api
      - read_api
    networks:
      - backend
    ports:
      - '9999:80'
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '20MB'

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

volumes:
  socket_data:
