services:
  api1:
    image: jrblatt/rinha-de-backend-2025-nodejs:latest
    container_name: api1
    hostname: api1
    environment:
      - SOCKET_PATH=/tmp/api1.sock
      - FOREIGN_STATE=api2
      - MODE=🔥
    volumes:
      - nodejsfaf:/tmp/
    networks:
      - payment-processor
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: 155MB

  api2:
    image: jrblatt/rinha-de-backend-2025-nodejs:latest
    container_name: api2
    hostname: api2
    environment:
      - SOCKET_PATH=/tmp/api2.sock
      - FOREIGN_STATE=api1
      - MODE=🔥
    volumes:
      - nodejsfaf:/tmp/
    networks:
      - payment-processor
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: 155MB

  nginx:
    image: openresty/openresty:bullseye
    container_name: nginx
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - nodejsfaf:/tmp/
    depends_on:
      - api1
      - api2
    networks:
      - payment-processor
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 40MB

volumes:
  nodejsfaf:
    driver: local

networks:
  payment-processor:
    external: true
    driver: bridge
